ALTER TABLE "account" ALTER COLUMN "id" SET DATA TYPE varchar(512) USING "id"::varchar(512);--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "account_id" SET DATA TYPE varchar(512) USING "account_id"::varchar(512);--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "provider_id" SET DATA TYPE varchar(512) USING "provider_id"::varchar(512);--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "user_id" SET DATA TYPE varchar(512) USING "user_id"::varchar(512);--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "access_token" SET DATA TYPE varchar(512) USING "access_token"::varchar(512);--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "refresh_token" SET DATA TYPE varchar(512) USING "refresh_token"::varchar(512);--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "id_token" SET DATA TYPE varchar(512) USING "id_token"::varchar(512);--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "scope" SET DATA TYPE varchar(512) USING "scope"::varchar(512);--> statement-breakpoint
ALTER TABLE "account" ALTER COLUMN "password" SET DATA TYPE varchar(512) USING "password"::varchar(512);--> statement-breakpoint
ALTER TABLE "session" ALTER COLUMN "id" SET DATA TYPE varchar(512) USING "id"::varchar(512);--> statement-breakpoint
ALTER TABLE "session" ALTER COLUMN "token" SET DATA TYPE varchar(512) USING "token"::varchar(512);--> statement-breakpoint
ALTER TABLE "session" ALTER COLUMN "ip_address" SET DATA TYPE varchar(512) USING "ip_address"::varchar(512);--> statement-breakpoint
ALTER TABLE "session" ALTER COLUMN "user_agent" SET DATA TYPE varchar(512) USING "user_agent"::varchar(512);--> statement-breakpoint
ALTER TABLE "session" ALTER COLUMN "user_id" SET DATA TYPE varchar(512) USING "user_id"::varchar(512);--> statement-breakpoint
ALTER TABLE "sso_provider" ALTER COLUMN "id" SET DATA TYPE varchar(512) USING "id"::varchar(512);--> statement-breakpoint
ALTER TABLE "sso_provider" ALTER COLUMN "issuer" SET DATA TYPE varchar(512) USING "issuer"::varchar(512);--> statement-breakpoint
ALTER TABLE "sso_provider" ALTER COLUMN "oidc_config" SET DATA TYPE varchar(512) USING "oidc_config"::varchar(512);--> statement-breakpoint
ALTER TABLE "sso_provider" ALTER COLUMN "saml_config" SET DATA TYPE varchar(512) USING "saml_config"::varchar(512);--> statement-breakpoint
ALTER TABLE "sso_provider" ALTER COLUMN "user_id" SET DATA TYPE varchar(512) USING "user_id"::varchar(512);--> statement-breakpoint
ALTER TABLE "sso_provider" ALTER COLUMN "provider_id" SET DATA TYPE varchar(512) USING "provider_id"::varchar(512);--> statement-breakpoint
ALTER TABLE "sso_provider" ALTER COLUMN "organization_id" SET DATA TYPE varchar(512) USING "organization_id"::varchar(512);--> statement-breakpoint
ALTER TABLE "sso_provider" ALTER COLUMN "domain" SET DATA TYPE varchar(512) USING "domain"::varchar(512);--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "id" SET DATA TYPE varchar(512) USING "id"::varchar(512);--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "name" SET DATA TYPE varchar(512) USING "name"::varchar(512);--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "email" SET DATA TYPE varchar(512) USING "email"::varchar(512);--> statement-breakpoint
ALTER TABLE "user" ALTER COLUMN "image" SET DATA TYPE varchar(512) USING "image"::varchar(512);--> statement-breakpoint
ALTER TABLE "verification" ALTER COLUMN "id" SET DATA TYPE varchar(512) USING "id"::varchar(512);--> statement-breakpoint
ALTER TABLE "verification" ALTER COLUMN "identifier" SET DATA TYPE varchar(512) USING "identifier"::varchar(512);--> statement-breakpoint
ALTER TABLE "verification" ALTER COLUMN "value" SET DATA TYPE varchar(512) USING "value"::varchar(512);